### ISSUE TITLE
Support for Netty 4.0.30-Final

### ISSUE THREAD

**Issue by afkham** [cdapio/netty-http#22]
I have started working on migrating this code to Netty 4. You can find the work in progress code at https://github.com/afkham-azeez/netty-http. Do you have plans to move to Netty 4 in the near future? If so, I will be happy to provide a GitHub PR.

**Comment by nitinmotgi** [comment]
We would love to have this patch. Send in the PR when ready. Thanks for your contribution.

**Comment by cdancy** [comment]
@afkham @nitinmotgi @chtyim any updates here? Even if not implemented by this developer any plans within cask to bump to a newer version of netty?

**Comment by pims** [comment]
I just stumbled on `netty-http` and it seems to be a good foundation for what we’re trying to build.
My knowledge of Netty is very limited, but if there is an common effort to port to Netty 4, I’d like to contribute in any way I can.

@afkham what’s the status of your fork? Need help finishing it?

**Comment by blling** [comment]
nothing happend?

**Comment by chtyim** [comment]
PR opened to upgrade to netty-4.1 https://github.com/caskdata/netty-http/pull/46

**Comment by chtyim** [comment]
Issue resolved with the upgrade to netty 4.1
