### ISSUE TITLE
HandlerHook.java - Post call not including response.

### ISSUE THREAD

**Issue by nickweibel** [cdapio/netty-http#25]
We are trying to use your handler hook for pre/post handling. On the postCall method we only have access to the original request. It would be extremely useful if you included the response. I was originally intending to log the response body and response headers within this method.

void postCall(HttpRequest request, HttpResponseStatus status, HandlerInfo handlerInfo);

**Comment by sreevatsanraman** [comment]
We don't buffer the response that's the reason why we don't expose that in postCall method. 

If you want access to the response body you can add a channel handler to the netty pipeline and can have access to the response and the chunks. NettyHttpService allows you to add additional channel handlers using modifyChannelPipeline method. Please see the HttpServerTest for example: https://github.com/caskdata/netty-http/blob/develop/src/test/java/co/cask/http/HttpServerTest.java#L87-L92
The following code snippet will help in adding your own channel pipeline:

``` java
NettyHttpService.Builder builder = NettyHttpService.builder();
builder.modifyChannelPipeline(new Function<ChannelPipeline, ChannelPipeline>() {
  @Override
     public ChannelPipeline apply(ChannelPipeline channelPipeline) {
       channelPipeline.addBefore("dispatcher", "myHandler", new MyChannelUpStreamHandler());
       return channelPipeline;
     }
  });
```

**Comment by nickweibel** [comment]
Thank you! Please feel free to close this issue.
