### ISSUE TITLE
New release or expected to build from source?

### ISSUE THREAD

**Issue by cdancy** [cdapio/netty-http#37]
Are you guys doing new releases or is the idea one is suppose to fork and build from there?

**Comment by wolf31o2** [comment]
The releases are pushed to Maven Central. Are you unable to fetch them from there?

**Comment by cdancy** [comment]
Aaaahhhh gotcha. I was looking at the releases on github with the last one being done on 2014.

**Comment by wolf31o2** [comment]
Fair enough. We should probably tag those.

**Comment by cdancy** [comment]
Any interest in building with gradle over maven? There are various plugins which make publishing not only to maven central but to jcenter a breeze. Not to mention uploading the jar to github. I could take on the work here as I do this for [all of the projects I maintain](https://github.com/cdancy/bitbucket-rest).

**Comment by wolf31o2** [comment]
No interest, AFAIK. We used to use gradle in our organization and moved away from it to Maven, which fits our needs better.

**Comment by cdancy** [comment]
Sounds good. Thanks for the info!
