### ISSUE TITLE
Bump guava dependency to 19.0

### ISSUE THREAD

**Issue by cdancy** [cdapio/netty-http#38]
Any objections to bumping the guava dep to 19.0? I've got a project I want to incorporate this into but it has a dependency on 19.0. I rebuilt this project with 19.0 and did not find any compilation issues. I can submit the PR for this change if need be.

**Comment by chtyim** [comment]
Have you try using netty-http by excluding the guava 13 it brings and have a guava 19 as a direct dependency in your project? If that's work, you don't have to wait for netty-http to bump to guava 19. 

On a side note, I think we can remove usage of guava from netty-http library to make it more user friendly.

**Comment by cdancy** [comment]
@chtyim the project already brings in guava 19 ahead of the version you guys supply. I was more just going over this code and seeing what could be bumped up to newer versions so as to use the latest and greatest while not breaking anything.

**Comment by chtyim** [comment]
I see. We currently have other projects that uses guava 13 and netty-http. That makes the bumping of the guava in netty-http slightly tricky.

**Comment by cdancy** [comment]
Fair enough. We can close for now then. Thanks for the insight.
