### ISSUE TITLE
0.18.0 Release

### ISSUE THREAD

**Issue by kennethjor** [cdapio/netty-http#60]
Lots of changes since 0.17.0, including Netty 4. Would be nice to have this in a public release.

**Comment by chtyim** [comment]
We will be releasing 1.0.0, which includes updates to netty 4. It is a major version bump due to the API incompatibility between netty 3 and netty 4.

**Comment by chtyim** [comment]
@kennethjor We just released netty-http-1.0.0 and artifacts are already available via maven central.
