### ISSUE TITLE
Override default 404 handling

### ISSUE THREAD

**Issue by fatso83** [cdapio/netty-http#95]
As mentioned in https://github.com/cdapio/netty-http/issues/94#issuecomment-764726267 I was able to integrate this project successfully in an existing Netty based application, just by picking out the relevant pieces. At the moment, I add the `netty-http` handlers only if the current request matches a root context (like `/api/v1`). This is because the [default logic in this library is to return HTTP 404 if none of the routes match](https://github.com/cdapio/netty-http/blob/1a7819f0446ee4d4575c3505db6c386f2c9c45cb/src/main/java/io/cdap/http/internal/RequestRouter.java#L94-L102).

That does not work well with Single Page Applications with client side routing that relies on having `index.html` returned for all non-matching routes on the server!

This is the current setup:
```java
        pipeline.addLast(restApi,
                new SimpleChannelInboundHandler<HttpRequest>(false) {
                    @Override
                    protected void channelRead0(ChannelHandlerContext ctx, HttpRequest msg) throws Exception {
                        final var hasRouter = pipeline.get("router") != null;

                        if (msg.uri().startsWith("/api")) {

                            if (!hasRouter) {
                                final RequestRouter requestRouter = setupRequestRouter(singletonList(new PingHandler()));

                                final var pipeline = ctx.pipeline();
                                pipeline.addAfter(restApi, "router", requestRouter);
                                pipeline.addAfter("router", "dispatcher", new HttpDispatcher());
                            }
                        } else {
                            if (hasRouter) {
                                pipeline.remove("router");
                                pipeline.remove("dispatcher");
                            }
                        }
                        ctx.fireChannelRead(msg);
                    }
                });
```

What I envision is making today's [non-matching routes handling user configurable](https://github.com/cdapio/netty-http/blob/v1.5.0/src/main/java/io/cdap/http/internal/HttpResourceHandler.java#L231). To get this to work for us, we would only need to make the handler pass the request on to the next Netty handler in the queue, so a simple `boolean` flag would suffice.

I am not totally sure how the handling in [RequestRouter](https://github.com/cdapio/netty-http/blob/1a7819f0446ee4d4575c3505db6c386f2c9c45cb/src/main/java/io/cdap/http/internal/RequestRouter.java#L94-L102) compares to the one in [HttpResourceHandler](https://github.com/cdapio/netty-http/blob/v1.5.0/src/main/java/io/cdap/http/internal/HttpResourceHandler.java#L231), though.

In any case, I could make the necessary changes, but is this something the project would/could accept?

**Comment by chtyim** [comment]
You can achieve the default handling by adding a method with path `@Path("/**")` as a catch-all handler. The path matching logic in the library matches from most specific to generic wildcard.

**Comment by fatso83** [comment]
That was not what I envisioned, but maybe I could get that to work ... 🤔  What I originally wanted was to let the request follow the Chain-of-responsibility pattern to the next handler in the chain, if none of the netty-http `HttpRequestHandler`s could handle the request. Today the `netty-http` handler is in the middle of the chain, with some handlers following it, but if I let this be the very last handler I guess that would work, if I just rewrite some of the existing Netty Handlers that follow it into `netty-http` HttpRequestHandlers. Thanks for the tip.
